[phases.setup]
nixPkgs = ["ffmpeg", "liberation_ttf"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "export PATH=$PATH:/nix/var/nix/profiles/default/bin && python server.py"
